# Securely send your logs to Loggly using TLS encryption. 
# https://www.loggly.com/docs/rsyslog-tls-configuration/

- name: TLS | Install required software
  package:
    name: rsyslog-gnutls
    state: present

- block:
  - name: TLS | Install required software
    package:
      name: ca-certificates
      state: present
  when: services[rsyslog_srv].cert_name is not defined

## use specific certificate
- block:
  - name: TLS | Ensure directory exists
    file:
      path: '{{ rsyslog_cert_path }}'
      state: directory
  - name: TLS | check for existing certificates
    shell: ls -l {{ rsyslog_cert_path }} # noqa 305
    register: capture
    changed_when: false
  - name: TLS | remove unexpected certificates
    file: path={{ rsyslog_cert_path }}/{{ item }} state=absent
    with_items: '{{ capture.stdout_lines }}'
    when: item != rsyslog_cert
    ignore_errors: True
  - name: TLS | Create certificate folder for tls
    file:
      path: "{{ rsyslog_cert_path }}"
      state: directory
  - name: TLS | Download certificate
    get_url:
      url: "{{ services[rsyslog_srv].cert_path }}{{ services[rsyslog_srv].cert_name }}"
      dest: "{{ rsyslog_cert_path }}/{{ rsyslog_cert }}"
  when: services[rsyslog_srv].cert_name is defined